# Generated by Django 2.1.5 on 2019-02-01 09:26

from django.db import migrations, models
import restapi.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=128)),
                ('location_type', models.CharField(choices=[(restapi.enums.LocationType('Country'), 'Country'), (restapi.enums.LocationType('City'), 'City'), (restapi.enums.LocationType('Zip'), 'Zip')], max_length=10)),
                ('location_string', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[(restapi.enums.LocationType('Country'), 'Country'), (restapi.enums.LocationType('City'), 'City'), (restapi.enums.LocationType('Zip'), 'Zip')], default=restapi.enums.LeadStatus('Created'), max_length=10)),
                ('communication', models.CharField(max_length=512)),
                ('tags', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
