# Generated by Django 2.1.5 on 2019-02-01 10:34

from django.db import migrations
import enumchoicefield.fields
import restapi.enums


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location_type',
            field=enumchoicefield.fields.EnumChoiceField(default=restapi.enums.LocationType(1), enum_class=restapi.enums.LocationType, max_length=7),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=restapi.enums.LeadStatus(1), enum_class=restapi.enums.LeadStatus, max_length=9),
        ),
    ]
