# Generated by Django 2.1.5 on 2019-02-01 09:42

from django.db import migrations, models
import restapi.enums


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[(restapi.enums.LeadStatus('Created'), 'Created'), (restapi.enums.LeadStatus('Contacted'), 'Contacted'), (restapi.enums.LeadStatus('Converted'), 'Converted')], default=restapi.enums.LeadStatus('Created'), max_length=10),
        ),
    ]
